FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential python

COPY . /full-stack-hello
WORKDIR /full-stack-hello
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /full-stack-hello/as_exec /
